# ===============================
# Application
# ===============================

spring.application.name=shop1

# Profile ???????
# ??? ???? ???? ????? ???? ????? ???? ??????
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}