server {
    listen 80;
    server_name localhost;

    # حداکثر حجم فایل آپلودی
    client_max_body_size 20M;

    location / {
        # در داکر، کانتینر اسپرینگ‌بوت با نام backend شناخته می‌شود
        proxy_pass http://backend:8080;

        # ارسال هدرهای مهم برای امنیت و شناسایی IP کلاینت
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}